name: Version Check

on: [push, pull_request]

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get the latest tag
      id: get-latest-tag
      run: echo "LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Display the latest tag
      run: echo "The latest tag is ${{ env.LATEST_TAG }}"
