name: Version Check

on: [push]

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch all tags and complete history
      run: git fetch --prune --unshallow --tags

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "v0.0.0")
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Determine new version
      id: new_version
      run: |
        latest_tag=${{ env.latest_tag }}
        IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
        major=${version_parts[0]}
        minor=${version_parts[1]}
        patch=${version_parts[2]}

        # Determine increment type based on PR title
        pr_title="${{ github.event.pull_request.title }}"
        if [[ "$pr_title" == *"major"* ]]; then
          major=$((major + 1))
          minor=0
          patch=0
        elif [[ "$pr_title" == *"minor"* ]]; then
          minor=$((minor + 1))
          patch=0
        else
          patch=$((patch + 1))
        fi

        new_version="v$major.$minor.$patch"
        echo "new_version=$new_version" >> $GITHUB_ENV
        echo "New version: $new_version"

    - name: Configure Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Create GitHub Tag
      id: create_tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a ${{ env.new_version }} -m "Release ${{ env.new_version }}"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ env.new_version }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.new_version }}
        release_name: ${{ env.new_version }}
        body: "Automated release for version ${{ env.new_version }}"
        draft: false
        prerelease: false
